#!/bin/bash

cd /home/facoteam1/stores/spreestore/current

# commands to generate keys and certificates
openssl genrsa -des3 -out server.key 1024
openssl req -new -key server.key -out server.csr

# remove the passphrase
cp server.key server.key.org
openssl rsa -in server.key.org -out server.key

# sign the ssl certificate
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

# copy the keys and certificate to the etc/ssl/keys and etc/ssl/certs

sudo cp /home/facoteam1/stores/spreestore/current/server.key /etc/ssl/keys/

sudo cp /home/facoteam1/stores/spreestore/current/server.crt /etc/ssl/certs/
